### ISSUE TITLE
Clean up of STI initialization submodule

### ISSUE THREAD

**Issue by smjenness** [statnet/EpiModelHIV#23]
These are mainly stylistic edits to make in the `init_status_sti_msm` function:

- [x] Several "defined but not used" variables that may be removed from the function. In Rstudio, under tools --> global options --> code --> diagnostics, check all of the check boxes in this tab. Relatedly, make sure that the two check boxes under the code --> saving, make sure these two checkboxes are checked. If you had planned to use these but just not currently, then keep them. 
- [x] Are you actually using the `stage.time.syph` variable for progression, as it appears like you are basing progression based on `time.since.inf.syph` instead. If it's not being used outside this submodule, you shouldn't need to store it on `dat$attr`
- [x] The `time.since.inf` variables (e.g., on ln 844) are not named usefully. Instead should be related to time since stage started.
- [x] Insert section markers (code --> insert section) for each of the three diseases in this function
- [x] Lines 754-805 set a large number of attributes to NA, and then they are never operated upon during the function, just written to `dat$attr` at the end. For clarity, just write each of these directly as `dat$attr$X <- rep(NA, num)` at the end of the function.
- [x] I think we should write everything out to `dat$attr` at the end of the function to increase clarity. That includes existing code from me for GC and CT. You can set that as a separate section header to further create the distinction.

**Comment by kweiss2** [comment]
Regarding the last check box - do we want move toward this for the sti.R modules as well (sti_tx, sti_recov, sti_trans modules)?

**Comment by smjenness** [comment]
I think that's a good idea
