### ISSUE TITLE
Represent persistent partnership ID in disclosure and partnership matrices

### ISSUE THREAD

**Issue by smjenness** [statnet/EpiModelHIV#29]
Instead of retaining two columns in these matrices with `uid[id1], uid[id2]`, form the unique partnership id and store as
```r
uid[id1] * 1e7 + uid[id2]
```
and save in one column. This should also cut down on the computational time in creating these ids within each module.

**Comment by kweiss2** [comment]
Re: risk history indications which are partner-specific (e.g. number of partners) - thoughts on the best way to pull out individual uids from a new persistent partnership ID? The issue with using something like regEx or pulling the first X numbers from a partnership ID is that, depending on the time of the intervention start, it could be a 1-, 2-, 3-, 4-, or 5-digit uid

**Comment by kweiss2** [comment]
In the follow-up period, this is more easily addressed, as everyone pretty much has 5-digit uids, so it could be done using a regEx or other approach to pull out the first 5 and last 5 digits. This would simplify it for our purposes, but wouldn't work if people wanted to test risk history starting earlier than 30-40 years

**Comment by smjenness** [comment]
We decided to close this issue for the reason mentioned above
