### ISSUE TITLE
Dual-site (or three-site?) infection to include syphilis

### ISSUE THREAD

**Issue by kweiss2** [statnet/EpiModelHIV#38]
@smjenness, how far should we go with this? Build structure for each combo but set to the same relative risk?
Possible combos:
- rGC and rCT
- rGC and syphilis
- rCT and syphilis
- rGC, rCT, and syphilis
- uGC and uCT
- uGC and syphilis
- uCT and syphilis
- uGC, uCT, and syphilis

**Comment by kweiss2** [comment]
Also, do we want to extend this for increased risk of HIV transmission? e.g. when HIV+ insertive partner has syphilis and urethral GC @jsjone2

**Comment by smjenness** [comment]
I would suggest that this be driven by any empirical literature on this topic, first and foremost, if it exists. If not, then how others have modeled co-infections (I realize that number may just be us at this point!). If not, then aim for model parsimony. I like the approach of an additive factor [0, 1] that could be fixed across all potential coinfections, as we currently have implemented for GC/CT. Thoughts?

**Comment by kweiss2** [comment]
I think the empirical literature is very much lacking on dual site infections, I haven't seen others model co-infection and its influence on acquisition/transmission of a third infection. I think the additive approach makes the most sense - I was thinking about summing the number of site-specific STI infections for each individual at each time point (max = 3 - NG, CT, syphilis), with perhaps a different additive factor if all three infections are present. Anything we add seems to be exploratory!

**Comment by smjenness** [comment]
I think @jsjone2 should weigh in here too, as this is his domain. And perhaps this is a good topic for the CDC meeting on Friday.
