### ISSUE TITLE
Change GC to NG in the codebase

### ISSUE THREAD

**Issue by kweiss2** [statnet/EpiModelHIV#40]

**Comment by kweiss2** [comment]
@smjenness if necessary

**Comment by smjenness** [comment]
This is just a switch to the variable names? Go for it!

**Comment by smjenness** [comment]
@kweiss2 Is this still open, or did you handle this in your branch?

**Comment by kweiss2** [comment]
This was tabled on my end due to more pressing code changes - still debating whether it is worth doing so

**Comment by smjenness** [comment]
Closing, not needed...
