### ISSUE TITLE
New Note - R_registerRoutines and R_useDynamicSymbols

### ISSUE THREAD

**Issue by kweiss2** [statnet/EpiModelHIV#44]
New note during build and reload: 
```
File 'EpiModelHIV/libs/x64/EpiModelHIV.dll':
  Found no calls to: 'R_registerRoutines', 'R_useDynamicSymbols'
It is good practice to register native routines and to disable symbol search
```

@smjenness - Wasn't sure about the best course/location of fixing it right now, so creating an issue rather than just trying to address it right now. Looks like a line or so might need to be added to any Cpp files

Suggested that a single call to this R file (https://raw.githubusercontent.com/stan-dev/rstantools/master/R/init_cpp.R) might address it

(https://github.com/RcppCore/Rcpp/issues/636)
(https://github.com/RcppCore/Rcpp/issues/651)
(https://stackoverflow.com/questions/42313373/r-cmd-check-note-found-no-calls-to-r-registerroutines-r-usedynamicsymbols)
(https://github.com/kevinushey/sourcetools/blob/master/R/register.R)

**Comment by smjenness** [comment]
This has been fixed...
