### ISSUE TITLE
HIV progress module

### ISSUE THREAD

**Issue by thednainus** [statnet/EpiModelHIV#56]
Hello,

I am wondering if the new values for `stage` should be updated only at the end of the function?
https://github.com/statnet/EpiModelHIV/blob/CombPrev/R/mod.hivprogress.R

I could **not** test this specific function, but a similar version. 
For example:
when getting the index for `stage == 2` 
 https://github.com/statnet/EpiModelHIV/blob/26ea27a0a89f5b78a2b0123fc74875b0f5b26b44/R/mod.hivprogress.R#L64

then in line 68, it could potentially be selected again. Although, it might not be selected again based on `time.since.inf`
https://github.com/statnet/EpiModelHIV/blob/26ea27a0a89f5b78a2b0123fc74875b0f5b26b44/R/mod.hivprogress.R#L68

Cheers,
Fabricia.

**Comment by smjenness** [comment]
Thanks @thednainus -- in this case, you are right they are mutually exclusive because of the additional condition based on time.since.inf (people progressing to chronic stage must have a time.since.inf that is higher).
